# Generated by Django 5.1.6 on 2025-03-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='base.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
