# Generated by Django 5.1.6 on 2025-03-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_is_shared_post_original_post_post_share_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='post',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='share_count',
        ),
    ]
