# Generated by Django 5.1.6 on 2025-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
