# Generated by Django 5.1.6 on 2025-03-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='encrypted_private_key',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
